### ISSUE TITLE
Missing ImGui library

### ISSUE THREAD

**Issue by domthibault** [jamesb93/ReaCoMa-Installer#1]
Hi James, 

Thank you for the installer version of reacoma! I just installer the package, the scripts are in my action list. But when I launch a script I get this error message : "cannot open /Users/dthibault/Library/Application Support/REAPER/Scripts/ReaTeam Extensions/API/imgui.lua: No such file or directory"

I had to install ReaImGui from ReaPack and relaunch Reaper for it to work. 

Just a heads up!

Dominic

**Comment by jamesb93** [comment]
Hey @domthibault! The installer doesn't actually install ReaImGui. That part is now up to the user as its becoming hard to maintain versions for different users and such.

The script _should_ have warned you that you didn't have it installed, so I think it's possible you had a botched install or an old one where the imgui.lua script was elsewhere. In any case glad its fixed!
